export const constants = {
  apiEndPoints: {
    getMenuPermissions: 'Menu/GetPermissions',
    login: 'Session/Login',
    logout: 'Session/Logout',
    renew: 'Session/Renew',
    menu: 'Menu',
    getProduct:'Product',
    getProductByID:'Product',
    createProduct:'Product',
    updateProduct:'Product',
    deleteProduct:'Product',
    productCharges:'ProductCharges',
    disseminationLimit: 'DisseminationLimit',
    deviationLimit: 'DeviationLimits',
    createCustomer: 'CustomerAggregator',
    getAllCustomer: 'Customer/GetAllCustomers',
    customerRating: 'CustomerRatings',
    getCustomerDL: 'CustDisseminationLimit/GetDLForCustomerProduct',
    saveCustomerDL: 'CustDisseminationLimit/SaveDLForCustomerProduct',
    getCustomerList: 'Customer/GetCustomers',
    getbankdetailsIFSC: 'VerifyBankAccount/getbankdetailsIFSC',
    verifyBankAccount: 'VerifyBankAccount/VerifyBankAccount',
    updateCustomer: 'CustomerAggregator/UpdateCustomer',
    GetDocumentTypeDetails: 'DocumentType/GetDocumentTypeDetails',
    getCustomerById:'CustomerAggregator/GetCustomerById',
  },
};
