import { Injectable } from "@angular/core";
import { BehaviorSubject, Subject } from "rxjs";


@Injectable({ providedIn: 'root' })

export class LoginService {
    private mySubject = new Subject<string>();
    constructor() { }

    sendValue(value: string): void {
        this.mySubject.next(value);
    }

    getSubject(): Subject<string> {
        return this.mySubject;
    }

    getMenusStatic() {
        const loginStat = {
            data: {
                menu: [
                    {
                        menuId: 1905,
                        menuName: "News & Greetings Creation",
                        routePath: "app/organization/news-greetings-creation",
                        displayOrder: 8,
                        moduleId: null,
                        icon: "",
                        parentId: 7,
                    },
                    {
                        menuId: 4,
                        menuName: "Master Settings",
                        routePath: "",
                        displayOrder: 4,
                        moduleId: null,
                        icon: "ri ri-settings-2-line",
                        parentId: 0,
                    },
                    {
                        menuId: 6,
                        menuName: "User",
                        routePath: "#",
                        displayOrder: 1,
                        moduleId: null,
                        icon: "",
                        parentId: 4,
                    },
                    {
                        menuId: 1849,
                        menuName: "User Creation",
                        routePath: "app/user/create",
                        displayOrder: 4,
                        moduleId: null,
                        icon: "",
                        parentId: 6,
                    },
                    {
                        menuId: 1874,
                        menuName: "Role Creation",
                        routePath: "app/user/role-create",
                        displayOrder: 2,
                        moduleId: null,
                        icon: "",
                        parentId: 6,
                    },
                    {
                        menuId: 1875,
                        menuName: "Role  Permission",
                        routePath: "app/user/role-permission",
                        displayOrder: 5,
                        moduleId: null,
                        icon: "",
                        parentId: 6,
                    },
                    {
                        menuId: 1907,
                        menuName: "Multi Branch User Access Creation",
                        routePath: "/app/user/multi-branch-create",
                        displayOrder: 7,
                        moduleId: null,
                        icon: "",
                        parentId: 6,
                    },
                    {
                        menuId: 1883,
                        menuName: "Scheme Listing",
                        routePath: "app/others/scheme-list",
                        displayOrder: 1,
                        moduleId: null,
                        icon: "",
                        parentId: 1882,
                    },
                    {
                        menuId: 1884,
                        menuName: "Scheme Creation",
                        routePath: "app/others/scheme-create",
                        displayOrder: 1,
                        moduleId: null,
                        icon: "",
                        parentId: 1882,
                    },
                    {
                        menuId: 1896,
                        menuName: "Multi Branch User Access Listing",
                        routePath: "app/user/multi-branch-list",
                        displayOrder: 6,
                        moduleId: null,
                        icon: "",
                        parentId: 6,
                    },
                    {
                        menuId: 1882,
                        menuName: "Scheme Management",
                        routePath: "",
                        displayOrder: 4,
                        moduleId: null,
                        icon: "",
                        parentId: 4,
                    },
                    {
                        menuId: 1871,
                        menuName: "User Listing",
                        routePath: "app/user/list",
                        displayOrder: 3,
                        moduleId: null,
                        icon: "",
                        parentId: 6,
                    },
                    {
                        menuId: 1873,
                        menuName: "Role Listing",
                        routePath: "app/user/role-list",
                        displayOrder: 1,
                        moduleId: null,
                        icon: "",
                        parentId: 6,
                    },
                    {
                        menuId: 189,
                        menuName: "Current Market Rate Listing",
                        routePath: "/Settings/Product/frmCurrentMarketRatelisting.aspx",
                        displayOrder: 9,
                        moduleId: null,
                        icon: "",
                        parentId: 19,
                    },
                    {
                        menuId: 1862,
                        menuName: "Product Listing",
                        routePath: "app/product/list",
                        displayOrder: 1,
                        moduleId: null,
                        icon: "",
                        parentId: 19,
                    },
                    {
                        menuId: 1864,
                        menuName: "Item Nature Listing",
                        routePath: "app/product/item-nature-list",
                        displayOrder: 3,
                        moduleId: null,
                        icon: "",
                        parentId: 19,
                    },
                    {
                        menuId: 1867,
                        menuName: "Unit Group Listing",
                        routePath: "app/product/unit-group-list",
                        displayOrder: 5,
                        moduleId: null,
                        icon: "",
                        parentId: 19,
                    },
                    {
                        menuId: 1865,
                        menuName: "Item Nature Creation",
                        routePath: "app/product/item-nature-create",
                        displayOrder: 4,
                        moduleId: null,
                        icon: "",
                        parentId: 19,
                    },
                    {
                        menuId: 190,
                        menuName: "Enable User Activities",
                        routePath: "/Settings/User/frmUserApproval.aspx",
                        displayOrder: 5,
                        moduleId: null,
                        icon: "",
                        parentId: 6,
                    },
                    {
                        menuId: 193,
                        menuName: "Upload Per Gram Rate",
                        routePath: "/Settings/Product/frmUpdatePerGramRate.aspx",
                        displayOrder: 12,
                        moduleId: null,
                        icon: "",
                        parentId: 19,
                    },
                    {
                        menuId: 215,
                        menuName: "Employee Management",
                        routePath: "/Settings/Employee/frmEmployeeSearch.aspx",
                        displayOrder: 7,
                        moduleId: null,
                        icon: "",
                        parentId: 6,
                    },
                    {
                        menuId: 262,
                        menuName: "Scheme Detail Listing",
                        routePath:
                            "/Settings/Product/frmProductSchemeListing.aspx?Type=SDL",
                        displayOrder: 13,
                        moduleId: null,
                        icon: "",
                        parentId: 19,
                    },
                    {
                        menuId: 19,
                        menuName: "Product",
                        routePath: "#",
                        displayOrder: 3,
                        moduleId: null,
                        icon: "",
                        parentId: 4,
                    },
                    {
                        menuId: 7,
                        menuName: "Organization",
                        routePath: "#",
                        displayOrder: 2,
                        moduleId: null,
                        icon: "",
                        parentId: 4,
                    },
                    {
                        menuId: 16,
                        menuName: "Holiday Listing",
                        routePath: "app/mastersettings/holiday-list",
                        displayOrder: 3,
                        moduleId: null,
                        icon: "",
                        parentId: 7,
                    },
                    {
                        menuId: 17,
                        menuName: "Special Working Day Listing",
                        routePath: "app/mastersettings/specialworkingday-list",
                        displayOrder: 5,
                        moduleId: null,
                        icon: "",
                        parentId: 7,
                    },
                    {
                        menuId: 1868,
                        menuName: "Unit Group Creation",
                        routePath: "app/product/unit-group-create",
                        displayOrder: 5,
                        moduleId: null,
                        icon: "",
                        parentId: 19,
                    },
                    {
                        menuId: 1877,
                        menuName: "Attach Nature Creation",
                        routePath: "app/mastersettings/product-nature-create",
                        displayOrder: 6,
                        moduleId: null,
                        icon: "",
                        parentId: 19,
                    },
                    {
                        menuId: 1885,
                        menuName: "Other Settings",
                        routePath: "",
                        displayOrder: 5,
                        moduleId: null,
                        icon: "",
                        parentId: 4,
                    },
                    {
                        menuId: 1870,
                        menuName: "Organization Creation",
                        routePath: "app/organization/create",
                        displayOrder: 2,
                        moduleId: null,
                        icon: "",
                        parentId: 7,
                    },
                    {
                        menuId: 1879,
                        menuName: "Holiday Creation",
                        routePath: "app/mastersettings/holiday-create",
                        displayOrder: 4,
                        moduleId: null,
                        icon: "",
                        parentId: 7,
                    },
                    {
                        menuId: 1895,
                        menuName: "News & Greetings Listing",
                        routePath: "app/organization/news-greetings-list",
                        displayOrder: 7,
                        moduleId: null,
                        icon: "",
                        parentId: 7,
                    },
                    {
                        menuId: 1863,
                        menuName: "Product Creation",
                        routePath: "app/product/create",
                        displayOrder: 2,
                        moduleId: null,
                        icon: "",
                        parentId: 19,
                    },
                    {
                        menuId: 1876,
                        menuName: "Attach Nature Listing",
                        routePath: "app/mastersettings/product-nature-list",
                        displayOrder: 6,
                        moduleId: null,
                        icon: "",
                        parentId: 19,
                    },
                    {
                        menuId: 1881,
                        menuName: "Special Working Day Creation",
                        routePath: "app/mastersettings/specialworkingday-create",
                        displayOrder: 6,
                        moduleId: null,
                        icon: "",
                        parentId: 7,
                    },
                    {
                        menuId: 1886,
                        menuName: "District Management",
                        routePath: "app/mastersettings/district-management",
                        displayOrder: 1,
                        moduleId: null,
                        icon: "",
                        parentId: 1885,
                    },
                    {
                        menuId: 1869,
                        menuName: "Organization Listing",
                        routePath: "app/organization/list",
                        displayOrder: 1,
                        moduleId: null,
                        icon: "",
                        parentId: 7,
                    },
                ],
                userUnitResponseToUI: {
                    orgUnitName: "MUTHOOT GROUP",
                    orgUnitCode: "GRP01",
                    eodDate: "2022-01-01T00:00:00",
                    displayName: "ANN MATHEW",
                    levelId: 1,
                    levelOrder: 1,
                    orgUnitId: 5150,
                    companyId: 12,
                },
            },
            statusCode: "200",
            statusMessage: "Success",
            correlationId: "01J1CGXE0JXBTYMWMFT1ER6YBP",
        };
        return loginStat;
    }

}